AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Python Serverless Image Editor

Globals:
  Function:
    Timeout: 800
    MemorySize: 1536

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  # DependenciesLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: dependencies-layer
  #     Description: Dependencies Layer
  #     ContentUri: layer
  #     CompatibleRuntimes:
  #       - python3.7
  #       - python3.8
  #       - python3.9
  #   Metadata:
  #     BuildMethod: python3.9
  AppColorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app_color_functions.app
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: "arn:aws:s3:::images-editor-app-bucket/*"
      Events:
        ColorCodesText:
          Type: Api
          Properties:
            Path: /color-codes-text
            Method: POST
        ColorCodesChart:
          Type: Api
          Properties:
            Path: /color-codes-chart
            Method: POST
        RGBChannels:
          Type: Api
          Properties:
            Path: /rgb-channels
            Method: POST
        RGBHistogram:
          Type: Api
          Properties:
            Path: /rgb-histogram
            Method: POST
        GetResult:
          Type: Api
          Properties:
            Path: /get-result
            Method: GET
  AppConvertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app_convert_functions.app
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: "arn:aws:s3:::images-editor-app-bucket/*"
      Events:
        ConvertType:
          Type: Api
          Properties:
            Path: /convert-type
            Method: PATCH
  AppEditFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app_edit_functions.app
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: "arn:aws:s3:::images-editor-app-bucket/*"
      Events:
        FlipHorizontal:
          Type: Api
          Properties:
            Path: /flip-horizontal
            Method: PATCH
        FlipVetical:
          Type: Api
          Properties:
            Path: /flip-vertical
            Method: PATCH
        RotateClockwise:
          Type: Api
          Properties:
            Path: /rotate-clockwise
            Method: PATCH
        RotateCounterClockwise:
          Type: Api
          Properties:
            Path: /rotate-cclockwise
            Method: PATCH
        Rotate180:
          Type: Api
          Properties:
            Path: /rotate-180
            Method: PATCH
  AppManageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app_manage_images.app
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: "arn:aws:s3:::images-editor-app-bucket/*"
      Events:
        ResizeImage:
          Type: Api
          Properties:
            Path: /add-image
            Method: POST
  AppSizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app_size_functions.app
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: "arn:aws:s3:::images-editor-app-bucket/*"
      Events:
        ResizeImage:
          Type: Api
          Properties:
            Path: /resize-image
            Method: PATCH


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  ImageEditorApi:
    Description: API Gateway endpoint URL for Prod stage for ImageEditorApi function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ImageEditor/"
  AppColorFunction:
    Description: AppColor Lambda Function ARN
    Value: !GetAtt AppColorFunction.Arn
  AppColorFunctionIamRole:
    Description: Implicit IAM Role created for AppColor function
    Value: !GetAtt AppColorFunctionRole.Arn
  AppConvertFunction:
    Description: AppConvert Lambda Function ARN
    Value: !GetAtt AppConvertFunction.Arn
  AppConvertFunctionIamRole:
    Description: Implicit IAM Role created for AppConvert function
    Value: !GetAtt AppConvertFunctionRole.Arn
  AppEditFunction:
    Description: AppEdit Lambda Function ARN
    Value: !GetAtt AppEditFunction.Arn
  AppEditFunctionIamRole:
    Description: Implicit IAM Role created for AppEdit function
    Value: !GetAtt AppEditFunctionRole.Arn
  AppManageFunction:
    Description: AppManage Lambda Function ARN
    Value: !GetAtt AppManageFunction.Arn
  AppManageFunctionIamRole:
    Description: Implicit IAM Role created for AppManage function
    Value: !GetAtt AppManageFunctionRole.Arn
  AppSizeFunction:
    Description: AppSize Lambda Function ARN
    Value: !GetAtt AppSizeFunction.Arn
  AppSizeFunctionIamRole:
    Description: Implicit IAM Role created for AppSize function
    Value: !GetAtt AppSizeFunctionRole.Arn
